language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f ./project/docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed demellj/udagram-api-feed:v1
  - docker tag udagram-api-user demellj/udagram-api-user:v1
  - docker tag udagram-fontend demellj/udagram-fontend:v1
  - docker tag reverseproxy demellj/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push demellj/udagram-api-user:v1
  - docker push demellj/udagram-api-feed:v1
  - docker push demellj/reverseproxy:v1
  - docker push demellj/udagram-fontend:v1
