apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    service: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-reverseproxy
  template:
    metadata:
      labels:
        service: udagram-reverseproxy
    spec:
      restartPolicy: Always
      containers:
      - name: udagram-reverseproxy
        image: demellj/reverseproxy:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: env-config
